### PR TITLE
changes to instructions/README.md

### PR DESCRIPTION
**Pull request by estelita24601**
markdown formatting, fixed a couple typos, and adding some clarifications to instructions

### CODE REVIEW

**Comment by mlmiller751** [comment]
Not sure why I am receiving this
"Prof Mark" (he/him)
Mark L. Miller, Ph.D.
Khoury College of Computer Sciences
Northeastern University (Silicon Valley)




On Oct 20, 2024, at 3:53 PM, Estelita ***@***.***> wrote:


markdown formatting, fixed a couple typos, and adding some clarifications to instructions

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/CS5001-khoury/FlightCounter/pull/1<https://www.google.com/url?q=https://github.com/CS5001-khoury/FlightCounter/pull/1&source=gmail-imap&ust=1730069591000000&usg=AOvVaw21pdN3P5Msj3BBTkG3-4VH>

Commit Summary

  *   2b04360<https://www.google.com/url?q=https://github.com/CS5001-khoury/FlightCounter/pull/1/commits/2b04360259f0ded8238a638e759c6892379f930b&source=gmail-imap&ust=1730069591000000&usg=AOvVaw1rYr9YNr4eMther6sfDCSP> markdown formatting, fixed a couple typos and adding some clarifications to instructions

File Changes

(1 file<https://www.google.com/url?q=https://github.com/CS5001-khoury/FlightCounter/pull/1/files&source=gmail-imap&ust=1730069591000000&usg=AOvVaw0VfjBpB2dks39lNoDR6V18>)

  *   M instructions/README.md<https://www.google.com/url?q=https://github.com/CS5001-khoury/FlightCounter/pull/1/files%23diff-6a062bc9b26303d32e8db34fe20d6a1f31e2e7e0e05717e9bf074769103c412c&source=gmail-imap&ust=1730069591000000&usg=AOvVaw2HkldTF3MjZgTmAA7tiQQY> (91)

Patch Links:

  *   https://github.com/CS5001-khoury/FlightCounter/pull/1.patch<https://www.google.com/url?q=https://github.com/CS5001-khoury/FlightCounter/pull/1.patch&source=gmail-imap&ust=1730069591000000&usg=AOvVaw1upoDODyQZWh7PeA6nleb8>
  *   https://github.com/CS5001-khoury/FlightCounter/pull/1.diff<https://www.google.com/url?q=https://github.com/CS5001-khoury/FlightCounter/pull/1.diff&source=gmail-imap&ust=1730069591000000&usg=AOvVaw1qsT57ZATrxqHfW6XuwFjJ>

**Comment by lionelle** [comment]
@mlmiller751   - it is because you still have notifications on for this repo.  One of my TAs made a pull request for the assignment, and unless you have it set that you only see notifications if you are tagged - i think github notifies all repo folks by default (i think I set you as an owner when first set this up,,, will double check your permissions on my end also)

**Comment by lionelle** [comment]
yup, had you setup as an owner in addition to the instructors group (since I first created this when we were co teaching) just fixed that, so hopefully that will automatically reduce notifications.

**Comment by mlmiller751** [comment]
Thanks, Albert! I didn't recall this history! I appreciate your fine-tuning!

**Pull request merged**
